#!/bin/sh

ulimit -c unlimited

# Some systems have "truss" or "tusc" instead of "strace".
# The -f option tells strace to follow children too.
# The -o option tells strace where to send its output.
strace -f -o /tmp/rsync-$$.out rsync "${@}"
